### ISSUE TITLE
`records` object should be `record` (singular)

### ISSUE THREAD

**Issue by johnchaffee** [danbartlett-twilio/airtable-crud#1]
https://github.com/danbartlett-twilio/airtable-crud/blob/61792ef9518a58b3f91345c40739cdb49f21d2cc/functions/airtable/get-record-by-id.js#L25

Hey @danbartlett-twilio, 

You airtable-crud for Twilio Functions is very cool. Thanks for creating and sharing it.

I discovered a small bug in the `get-record-by-id` function. It returns a single `record` but the callback is expecting `records`.

If you change `records` to `record` on line 25 it fixes the problem.

**Comment by danbartlett-twilio** [comment]
Thanks for pointing that out, John! I updated the code...

**Comment by johnchaffee** [comment]
Fixed in a9a17e46b08d419b51aabad6b29f4c140b053649
